/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type AkuttCalling = {
  _id: string;
  _type: "akuttCalling";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  link?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type FirstAidInfo = {
  _id: string;
  _type: "firstAidInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  col1: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  col2: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type InstruktorLink = {
  _id: string;
  _type: "instruktorLink";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
  link: string;
  linkText: string;
  rank?: number;
};

export type Vedtekter = {
  _id: string;
  _type: "vedtekter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  lastUpdated: string;
};

export type Committee = {
  _id: string;
  _type: "committee";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  email?: string;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  headerImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  committeeImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type CourseOffering = {
  _id: string;
  _type: "courseOffering";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: string;
  linkText?: string;
  order: number;
  category: "timeplanfestet" | "committeevent" | "skillcourse" | "other";
};

export type MediaItem = {
  _id: string;
  _type: "mediaItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoUrl?: string;
  externalLink?: string;
  year: number;
  publishedAt?: string;
};

export type CarouselSlide = {
  _id: string;
  _type: "carouselSlide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  backgroundImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title: string;
  description: string;
  buttonText: string;
  buttonLink: string;
};

export type BoardMember = {
  _id: string;
  _type: "boardMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role: "boardLeader" | "subjectLeader" | "internalLeader" | "externalLeader" | "internalCoordinator" | "externalCoordinator" | "committeeLeader" | "instructorLeader" | "financialLeader" | "extraLeader" | "marketingLeader" | "sponsorLeader" | "equipmentLeader" | "secretary" | "mentorLeader";
  email?: string;
  activeFrom: string;
  activeTo: string;
  profileImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  PersonalImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = AkuttCalling | SanityImageCrop | SanityImageHotspot | FirstAidInfo | InstruktorLink | Vedtekter | Committee | Slug | CourseOffering | MediaItem | CarouselSlide | BoardMember | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: BOARD_MEMBERS_QUERY
// Query: *[_type == "boardMember"] | order(  select(    role == 'boardLeader' => 1,    role == 'subjectLeader' => 2,    role == 'internalLeader' => 3,    role == 'externalLeader' => 4,    role == 'internalCoordinator' => 5,    role == 'externalCoordinator' => 6,    role == 'committeeLeader' => 7,    role == 'instructorLeader' => 8,    role == 'financialLeader' => 9,    role == 'marketingLeader' => 10,    role == 'extraLeader' => 11,    role == 'sponsorLeader' => 12,    role == 'equipmentLeader' => 13,    role == 'secretary' => 14,    role == 'mentorLeader' => 15,    99  ) asc,  _createdAt asc) {  _id,  name,  slug,  role,  email,  age,  hometown,  profileImage,  PersonalImage,  bio,  activeFrom,  activeTo}
export type BOARD_MEMBERS_QUERYResult = Array<{
  _id: string;
  name: string;
  slug: Slug;
  role: "boardLeader" | "committeeLeader" | "equipmentLeader" | "externalCoordinator" | "externalLeader" | "extraLeader" | "financialLeader" | "instructorLeader" | "internalCoordinator" | "internalLeader" | "marketingLeader" | "mentorLeader" | "secretary" | "sponsorLeader" | "subjectLeader";
  email: string | null;
  age: null;
  hometown: null;
  profileImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  PersonalImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  activeFrom: string;
  activeTo: string;
}>;
// Variable: CURRENT_BOARD_MEMBERS_QUERY
// Query: *[_type == "boardMember" && activeTo >= now()] | order(  select(    role == 'boardLeader' => 1,    role == 'subjectLeader' => 2,    role == 'internalLeader' => 3,    role == 'externalLeader' => 4,    role == 'internalCoordinator' => 5,    role == 'externalCoordinator' => 6,    role == 'committeeLeader' => 7,    role == 'instructorLeader' => 8,    role == 'financialLeader' => 9,    role == 'marketingLeader' => 10,    role == 'extraLeader' => 11,    role == 'sponsorLeader' => 12,    role == 'equipmentLeader' => 13,    role == 'secretary' => 14,    role == 'mentorLeader' => 15,    99  ) asc,  _createdAt asc) {  _id,  name,  slug,  role,  email,  age,  hometown,  profileImage,  PersonalImage,  bio,  activeFrom,  activeTo}
export type CURRENT_BOARD_MEMBERS_QUERYResult = Array<{
  _id: string;
  name: string;
  slug: Slug;
  role: "boardLeader" | "committeeLeader" | "equipmentLeader" | "externalCoordinator" | "externalLeader" | "extraLeader" | "financialLeader" | "instructorLeader" | "internalCoordinator" | "internalLeader" | "marketingLeader" | "mentorLeader" | "secretary" | "sponsorLeader" | "subjectLeader";
  email: string | null;
  age: null;
  hometown: null;
  profileImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  PersonalImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  activeFrom: string;
  activeTo: string;
}>;
// Variable: BOARD_MEMBER_QUERY_BY_SLUG
// Query: *[_type == "boardMember" && slug.current == $slug][0] {  _id,  name,  slug,  role,  email,  age,  hometown,  profileImage,  PersonalImage,  bio,  order,  activeFrom,  activeTo}
export type BOARD_MEMBER_QUERY_BY_SLUGResult = {
  _id: string;
  name: string;
  slug: Slug;
  role: "boardLeader" | "committeeLeader" | "equipmentLeader" | "externalCoordinator" | "externalLeader" | "extraLeader" | "financialLeader" | "instructorLeader" | "internalCoordinator" | "internalLeader" | "marketingLeader" | "mentorLeader" | "secretary" | "sponsorLeader" | "subjectLeader";
  email: string | null;
  age: null;
  hometown: null;
  profileImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  PersonalImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  order: null;
  activeFrom: string;
  activeTo: string;
} | null;
// Variable: BOARD_MEMBER_QUERY_BY_ROLE
// Query: *[_type == "boardMember" && role == $role][0] {  _id,  name,  slug,  role,  email,  age,  hometown,  profileImage,  PersonalImage,  bio,  order,  activeFrom,  activeTo}
export type BOARD_MEMBER_QUERY_BY_ROLEResult = {
  _id: string;
  name: string;
  slug: Slug;
  role: "boardLeader" | "committeeLeader" | "equipmentLeader" | "externalCoordinator" | "externalLeader" | "extraLeader" | "financialLeader" | "instructorLeader" | "internalCoordinator" | "internalLeader" | "marketingLeader" | "mentorLeader" | "secretary" | "sponsorLeader" | "subjectLeader";
  email: string | null;
  age: null;
  hometown: null;
  profileImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  PersonalImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  order: null;
  activeFrom: string;
  activeTo: string;
} | null;
// Variable: CAROUSEL_SLIDES_QUERY
// Query: *[_type == "carouselSlide"] | order(order asc) {  _id,  backgroundImage,  title,  description,  buttonText,  buttonLink,  order}
export type CAROUSEL_SLIDES_QUERYResult = Array<{
  _id: string;
  backgroundImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title: string;
  description: string;
  buttonText: string;
  buttonLink: string;
  order: null;
}>;
// Variable: MEDIA_ITEMS_QUERY
// Query: *[_type == "mediaItem"] | order(order asc) {  _id,  title,  slug,  description,  thumbnail,  videoUrl,  externalLink,  linkText,  year,  order,  publishedAt}
export type MEDIA_ITEMS_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  videoUrl: string | null;
  externalLink: string | null;
  linkText: null;
  year: number;
  order: null;
  publishedAt: string | null;
}>;
// Variable: COURSE_OFFERINGS_QUERY
// Query: *[_type == "courseOffering"] | order(order asc) {  _id,  title,  description,  image,  link,  linkText,  order,  category}
export type COURSE_OFFERINGS_QUERYResult = Array<{
  _id: string;
  title: string;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link: string | null;
  linkText: string | null;
  order: number;
  category: "committeevent" | "other" | "skillcourse" | "timeplanfestet";
}>;
// Variable: COMMITTEES_QUERY
// Query: *[_type == "committee"] | order(order asc) {  _id,  name,  slug,  email,  logo,  shortDescription,  order}
export type COMMITTEES_QUERYResult = Array<{
  _id: string;
  name: string;
  slug: Slug;
  email: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription: null;
  order: number;
}>;
// Variable: COMMITTEE_QUERY
// Query: *[_type == "committee" && slug.current == $slug][0] {  _id,  name,  slug,  email,  logo,  description,  headerImage,  committeeImage,  order}
export type COMMITTEE_QUERYResult = {
  _id: string;
  name: string;
  slug: Slug;
  email: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  headerImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  committeeImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  order: number;
} | null;
// Variable: VEDTEKTER_QUERY
// Query: *[_type == "vedtekter"][0] {  _id,  content,  lastUpdated}
export type VEDTEKTER_QUERYResult = {
  _id: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  lastUpdated: string;
} | null;
// Variable: FIRST_AID_INFO_QUERY
// Query: *[_type == "firstAidInfo"][0] {  _id,  col1,  col2}
export type FIRST_AID_INFO_QUERYResult = {
  _id: string;
  col1: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  col2: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
} | null;
// Variable: INSTRUKT_LINKS_QUERY
// Query: *[_type == "instruktorLink"] | order(rank asc, _createdAt asc) {  _id,  title,  description,  link,  linkText,  rank}
export type INSTRUKT_LINKS_QUERYResult = Array<{
  _id: string;
  title: string;
  description: string | null;
  link: string;
  linkText: string;
  rank: number | null;
}>;
// Variable: AKUTTKALLING_QUERY
// Query: *[_type == "akuttCalling"][0] {  _id,  title,  content,  gallery,  link}
export type AKUTTKALLING_QUERYResult = {
  _id: string;
  title: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  gallery: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  link: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"boardMember\"] | order(\n  select(\n    role == 'boardLeader' => 1,\n    role == 'subjectLeader' => 2,\n    role == 'internalLeader' => 3,\n    role == 'externalLeader' => 4,\n    role == 'internalCoordinator' => 5,\n    role == 'externalCoordinator' => 6,\n    role == 'committeeLeader' => 7,\n    role == 'instructorLeader' => 8,\n    role == 'financialLeader' => 9,\n    role == 'marketingLeader' => 10,\n    role == 'extraLeader' => 11,\n    role == 'sponsorLeader' => 12,\n    role == 'equipmentLeader' => 13,\n    role == 'secretary' => 14,\n    role == 'mentorLeader' => 15,\n    99\n  ) asc,\n  _createdAt asc\n) {\n  _id,\n  name,\n  slug,\n  role,\n  email,\n  age,\n  hometown,\n  profileImage,\n  PersonalImage,\n  bio,\n  activeFrom,\n  activeTo\n}": BOARD_MEMBERS_QUERYResult;
    "*[_type == \"boardMember\" && activeTo >= now()] | order(\n  select(\n    role == 'boardLeader' => 1,\n    role == 'subjectLeader' => 2,\n    role == 'internalLeader' => 3,\n    role == 'externalLeader' => 4,\n    role == 'internalCoordinator' => 5,\n    role == 'externalCoordinator' => 6,\n    role == 'committeeLeader' => 7,\n    role == 'instructorLeader' => 8,\n    role == 'financialLeader' => 9,\n    role == 'marketingLeader' => 10,\n    role == 'extraLeader' => 11,\n    role == 'sponsorLeader' => 12,\n    role == 'equipmentLeader' => 13,\n    role == 'secretary' => 14,\n    role == 'mentorLeader' => 15,\n    99\n  ) asc,\n  _createdAt asc\n) {\n  _id,\n  name,\n  slug,\n  role,\n  email,\n  age,\n  hometown,\n  profileImage,\n  PersonalImage,\n  bio,\n  activeFrom,\n  activeTo\n}": CURRENT_BOARD_MEMBERS_QUERYResult;
    "*[_type == \"boardMember\" && slug.current == $slug][0] {\n  _id,\n  name,\n  slug,\n  role,\n  email,\n  age,\n  hometown,\n  profileImage,\n  PersonalImage,\n  bio,\n  order,\n  activeFrom,\n  activeTo\n}": BOARD_MEMBER_QUERY_BY_SLUGResult;
    "*[_type == \"boardMember\" && role == $role][0] {\n  _id,\n  name,\n  slug,\n  role,\n  email,\n  age,\n  hometown,\n  profileImage,\n  PersonalImage,\n  bio,\n  order,\n  activeFrom,\n  activeTo\n}": BOARD_MEMBER_QUERY_BY_ROLEResult;
    "*[_type == \"carouselSlide\"] | order(order asc) {\n  _id,\n  backgroundImage,\n  title,\n  description,\n  buttonText,\n  buttonLink,\n  order\n}": CAROUSEL_SLIDES_QUERYResult;
    "*[_type == \"mediaItem\"] | order(order asc) {\n  _id,\n  title,\n  slug,\n  description,\n  thumbnail,\n  videoUrl,\n  externalLink,\n  linkText,\n  year,\n  order,\n  publishedAt\n}": MEDIA_ITEMS_QUERYResult;
    "*[_type == \"courseOffering\"] | order(order asc) {\n  _id,\n  title,\n  description,\n  image,\n  link,\n  linkText,\n  order,\n  category\n}": COURSE_OFFERINGS_QUERYResult;
    "*[_type == \"committee\"] | order(order asc) {\n  _id,\n  name,\n  slug,\n  email,\n  logo,\n  shortDescription,\n  order\n}": COMMITTEES_QUERYResult;
    "*[_type == \"committee\" && slug.current == $slug][0] {\n  _id,\n  name,\n  slug,\n  email,\n  logo,\n  description,\n  headerImage,\n  committeeImage,\n  order\n}": COMMITTEE_QUERYResult;
    "*[_type == \"vedtekter\"][0] {\n  _id,\n  content,\n  lastUpdated\n}": VEDTEKTER_QUERYResult;
    "*[_type == \"firstAidInfo\"][0] {\n  _id,\n  col1,\n  col2\n}": FIRST_AID_INFO_QUERYResult;
    "*[_type == \"instruktorLink\"] | order(rank asc, _createdAt asc) {\n  _id,\n  title,\n  description,\n  link,\n  linkText,\n  rank\n}": INSTRUKT_LINKS_QUERYResult;
    "*[_type == \"akuttCalling\"][0] {\n  _id,\n  title,\n  content,\n  gallery,\n  link\n}": AKUTTKALLING_QUERYResult;
  }
}
